language: php
php:
- 7.1
cache:
  directories:
    - $HOME/.composer/cache

# We need MySQL 5.7 to test JSON columns
services:
  - docker

before_install:
  - sudo service mysql stop || sudo service mysql-5.6 stop || sudo stop mysql-5.6 || sudo stop mysql || echo "failed to stop mysql"
  - sudo docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root mysql:5.7

env:
  matrix:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""
before_script:
- composer update --prefer-dist $PREFER_LOWEST
script:
- "./vendor/bin/phpunit"
after_script:
- if [ -z "$PREFER_LOWEST" ]; then ./vendor/bin/coveralls -v; fi
